### ISSUE TITLE
Confilct with "Startify"?

### ISSUE THREAD

**Issue by ywpkwon** [CKolkey/.dotfiles#1]
Hey, thanks for the great neovim configuration. I'm trying to use `lazygit`. 
I start up my neovim with `Startify`. I'm not sure you are familiar with it. It's so convenient.

But when I'm on the first screen and run `lazygit`  (toggle on) and close (toggle off), it gives me empty space and the cursor in the air.
![image](https://user-images.githubusercontent.com/18429284/78727542-c7061880-78e9-11ea-9f58-d2c3d7889281.png)
 
Once I open another file and a buffer exists, it never happens (i.e., works fine). If a buffer is open, even with the `Startify` screen, it never happens. The error only happens, when I newly startup my neovim, and at `Startify` screen without any other buffer opened. 

Could you please check or advise?

**Comment by CKolkey** [comment]
It looks like it's related to this line https://github.com/CKolkey/.dotfiles/blob/f22c99cb09938c59065838c89ab35226901208e2/nvim_init.vim#L271

Take a look at how that method creates a floating window. It's calling `nvim_open_win` twice. Once for the 'outer' window (the one that shows a border), and a second time for the inner window after running the options through `CreatePadding()`. 

It looks like startify is causing some conflict where nvim closes one of the windows, but not both.

Hope that helps :)

**Comment by ywpkwon** [comment]
Thanks :)
